baseURL = "https://jovial-noether-d4ee9f.netlify.app"
languageCode = "en-us"

[params]
  contentTypes = ["projects", "members", "events"]

[permalinks]
  projects = "/:slug/"
  members = "/:slug/"
  events = "/:slug/"