baseURL = "https://metalab.netlify.app/"
languageCode = "en-us"
uglyURLs = true
theme = ["hugo-cloak-email"]
disableKinds = ["taxonomyTerm"]

[taxonomies]
  host = "host"

[params]
  contentTypes = ["projects", "members", "events"]
  timezoneBoston = "EDT"
  timezoneBerlin = "CEST"

[params.label]
  hostsBoth = "Harvard and Berlin"
  hostsDefault = "Harvard"
  hostsHeadline = "Projects hosted by %s"
  socialFacebookTitle = "Follow %s on Facebook"
  socialGithubTitle = "Follow %s on Github"
  socialHomepageTitle = "Visit %s’s website"
  socialInstagramTitle = "Follow %s on Instagram"
  socialLinkedinTitle = "Follow %s on LinkedIn"
  socialEmailTitle = "Contact %s via mail"
  socialSoundcloudTitle = "Follow %s on Soundcloud"
  socialTwitterTitle = "Follow %s on Twitter"
  socialVimeoTitle = "Follow %s on Vimeo"
  socialYouTubeTitle = "Follow %s on YouTube"
  socialMetalabSelf = "us"
  relatedMembers = "Involved"
  relatedProjects = "Related"
  relatedEvents = "Related"
  relatedLabelMembers = "member"
  relatedLabelProjects = "project"
  relatedLabelEvents = "event"
  boxCollaborator = "Collaborator"
  boxTime = "Time"
  boxHost = "Host"
  boxLocation = "Location"
  boxType = "Type"
  relatedLabelLinks = "Link"
  relatedLabelPressArticles = "Press article"
  memberAlumnus = "Alumnus"

[permalinks]
  projects = "/:slug/"
  members = "/:slug/"
  events = "/:slug/"
  alumni = "/:slug/"
  host = "/:slug/"

[markup.goldmark.renderer]
  hardWraps = true
  unsafe = true

[outputFormats]
  [outputFormats.Content]
    mediaType = "application/json"
    baseName = "content"
    isPlainText = true
    notAlternative = true
  [outputFormats.HTML]
    noUgly = true

[outputs]
  home = ["HTML", "Content", "RSS"]
  section = ["HTML", "RSS"]

[sitemap]
  filename = "sitemap.xml"