baseURL = "https://metalab.netlify.app/"
languageCode = "en-us"
uglyURLs = true
theme = ["hugo-cloak-email"]
disableKinds = ["taxonomyTerm"]

[taxonomies]
  host = "host"

[params]
  contentTypes = ["projects", "members", "events"]
  timezoneBoston = "EDT"
  timezoneBerlin = "CEST"

[permalinks]
  projects = "/:slug/"
  members = "/:slug/"
  events = "/:slug/"
  alumni = "/:slug/"
  host = "/:slug/"

[markup.goldmark.renderer]
  hardWraps = true
  unsafe = true

[outputFormats]
  [outputFormats.Content]
    mediaType = "application/json"
    baseName = "content"
    isPlainText = true
    notAlternative = true
  [outputFormats.HTML]
    noUgly = true

[outputs]
  home = ["HTML", "Content", "RSS"]
  section = ["HTML", "RSS"]

[sitemap]
  filename = "sitemap.xml"