languageCode = "en-us"
theme = ["hugo-cloak-email"]
buildFuture = true
uglyURLs = true

[taxonomies]
  host = "host"
  categories = "categories"

[params]
  contentTypes = ["projects", "members", "events"]
  slugHost = "host"

[permalinks]
  projects = "/p/:slug/"
  members = "/m/:slug/"
  events = "/e/:slug/"
  categories = "/type/:slug/"

[markup.goldmark.renderer]
  hardWraps = true
  unsafe = true

[outputFormats]
  [outputFormats.Content]
    mediaType = "application/json"
    baseName = "content"
    isPlainText = true
    notAlternative = true
  [outputFormats.Humans]
    mediaType = "text/plain"
    baseName = "humans"
    isPlainText = true
    notAlternative = true
  [outputFormats.Robots]
    mediaType = "text/plain"
    baseName = "robots"
    isPlainText = true
    notAlternative = true
  [outputFormats.HTML]
    noUgly = true
  [outputFormats.manifest]
    name = "manifest"
    baseName = "manifest"
    mediaType = "application/json"
    notAlternative = "true"
  [outputFormats.Calendar]
    protocol = "https://"

[outputs]
  home = ["HTML", "Content", "RSS", "Humans", "Robots", "Manifest"]
  section = ["HTML", "RSS", "Calendar"]

[sitemap]
  filename = "sitemap.xml"

[markup]
  [markup.highlight]
    style = "emacs"
