baseURL = "https://jovial-noether-d4ee9f.netlify.app"
languageCode = "en-us"
disableKinds = ["taxonomy", "taxonomyTerm"]
uglyURLs = true
theme = ["hugo-cloak-email"]

[params]
  contentTypes = ["projects", "members", "events"]
  timezoneBoston = "EDT"
  timezoneBostonLabel = "Boston"
  timezoneBerlin = "CEST"
  timezoneBerlinLabel = "Berlin"

[permalinks]
  projects = "/:slug/"
  members = "/:slug/"
  events = "/:slug/"
  alumni = "/:slug/"

[markup.goldmark.renderer]
  hardWraps = true
  unsafe = true

[outputFormats]
  [outputFormats.Content]
    mediaType = "application/json"
    baseName = "content"
    isPlainText = true
    notAlternative = true
  [outputFormats.HTML]
    noUgly = true

[outputs]
  home = ["HTML", "Content", "RSS"]
  section = ["HTML", "RSS"]

[sitemap]
  filename = "sitemap.xml"