[build]
command = "npm run build"

[build.environment]
  GO_IMPORT_PATH = "github.com/z3to/metalab-website"
  GO111MODULE = "on"

[context.production.environment]
HUGO_VERSION = "0.83.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"