[build]
command = "make build"
publish = "public"

[context.production.environment]
HUGO_VERSION = "0.96.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/content.json"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[[redirects]]
  from = "https://mlml.netlify.app/*"
  to = "https://mlml.io/:splat"
  status = 301
