[build]
command = "go run script.go && go run events.go && go run members.go && go run projects.go && hugo --gc --minify --config config/config.json,config.toml --ignoreCache"

[context.production.environment]
HUGO_VERSION = "0.83.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"